# Generated by Django 5.1.7 on 2025-03-08 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Folio')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('hora_apertura', models.TimeField(auto_now_add=True, verbose_name='Hora de Apertura')),
                ('estatus', models.CharField(choices=[('Abierta', 'Abierta'), ('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20, verbose_name='Estatus')),
                ('fecha_cierre', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Cierre')),
                ('hora_cierre', models.TimeField(blank=True, editable=False, null=True, verbose_name='Hora de Cierre')),
                ('llamada', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20, verbose_name='Llamada')),
                ('motivo', models.CharField(choices=[('Solicitud', 'Solicitud'), ('Queja', 'Queja'), ('Correctivo', 'Correctivo')], max_length=50, verbose_name='Motivo')),
                ('medio_recepcion', models.CharField(choices=[('Llamada', 'Llamada'), ('Correo', 'Correo'), ('Chat', 'Chat')], max_length=50, verbose_name='Medio de Recepción')),
                ('medio_contacto', models.CharField(choices=[('Página web', 'Página web'), ('Atención.cliente', 'Atención.cliente'), ('Referido', 'Referido')], max_length=50, verbose_name='Medio de Contacto')),
                ('area', models.CharField(choices=[('Ventas PDE', 'Ventas PDE'), ('Ventas ACT', 'Ventas ACT'), ('Medical', 'Medical')], max_length=50, verbose_name='Área')),
                ('localidad', models.CharField(choices=[('Matriz', 'Matriz'), ('Servicio', 'Servicio')], max_length=50, verbose_name='Localidad')),
                ('industria_sector', models.CharField(choices=[('Manufactura', 'Manufactura'), ('Servicios Profesionales', 'Servicios Profesionales'), ('Energía', 'Energía'), ('Gobierno', 'Gobierno')], max_length=50, verbose_name='Industria/Sector')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California')], max_length=50, verbose_name='Estado')),
                ('caso', models.TextField(verbose_name='Caso')),
                ('responsable_area', models.CharField(max_length=100, verbose_name='Responsable de Área')),
                ('responsable_solucion', models.CharField(max_length=100, verbose_name='Responsable de Solución')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono_local', models.CharField(max_length=20, verbose_name='Teléfono Local')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('asesor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
            ],
        ),
    ]
