# Generated by Django 5.1.7 on 2025-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envío de Cotización'),
        ),
        migrations.AddField(
            model_name='folio',
            name='fecha_primer_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Primer Contacto'),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primer Intento'),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Segundo Intento'),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tercer Intento'),
        ),
        migrations.AddField(
            model_name='folio',
            name='status_envio',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20, verbose_name='Estado Envío Cotización'),
        ),
        migrations.AddField(
            model_name='folio',
            name='status_primer_contacto',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20, verbose_name='Estado Primer Contacto'),
        ),
    ]
