# Generated by Django 5.1.7 on 2025-03-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0003_folio_fecha_envio_folio_fecha_primer_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='estado_envio',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20, verbose_name='Estado Envío Cotización'),
        ),
        migrations.AddField(
            model_name='folio',
            name='estado_primer_contacto',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20, verbose_name='Estado Primer Contacto'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('CDMX', 'CDMX')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='status_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envio_folios', to=settings.AUTH_USER_MODEL, verbose_name='Asesor Envío'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='status_primer_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primer_contacto_folios', to=settings.AUTH_USER_MODEL, verbose_name='Asesor Primer Contacto'),
        ),
    ]
