# Generated by Django 5.1.7 on 2025-03-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0004_folio_estado_envio_folio_estado_primer_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='intento_1',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='intento_2',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='intento_3',
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_envio_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_envio_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_envio_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_pc_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_pc_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folio',
            name='intento_pc_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folio',
            name='area',
            field=models.CharField(choices=[('Ventas PDE', 'Ventas PDE'), ('Ventas ACT', 'Ventas ACT'), ('Medical', 'Medical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='caso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='folio',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folio',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folio',
            name='cp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='folio',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='folio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='folio',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('CDMX', 'CDMX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estado_envio',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='estado_primer_contacto',
            field=models.CharField(choices=[('NO CONTESTAN', 'No Contestan'), ('NO EXISTE', 'No Existe'), ('NO SE ENCUENTRA', 'No Se Encuentra'), ('NÚMERO EQUIVOCADO', 'Número Equivocado'), ('REALIZADA', 'Realizada'), ('NO REALIZADA', 'No Realizada')], default='NO REALIZADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folio',
            name='fecha_primer_contacto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folio',
            name='industria_sector',
            field=models.CharField(choices=[('Manufactura', 'Manufactura'), ('Servicios Profesionales', 'Servicios Profesionales'), ('Energía', 'Energía'), ('Gobierno', 'Gobierno')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='llamada',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='folio',
            name='localidad',
            field=models.CharField(choices=[('Matriz', 'Matriz'), ('Servicio', 'Servicio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='medio_contacto',
            field=models.CharField(choices=[('Página web', 'Página web'), ('Atención.cliente', 'Atención.cliente'), ('Referido', 'Referido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='medio_recepcion',
            field=models.CharField(choices=[('Llamada', 'Llamada'), ('Correo', 'Correo'), ('Chat', 'Chat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='motivo',
            field=models.CharField(choices=[('Solicitud', 'Solicitud'), ('Queja', 'Queja'), ('Correctivo', 'Correctivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='folio',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folio',
            name='responsable_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folio',
            name='responsable_solucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='folio',
            name='status_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envio_folios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folio',
            name='status_primer_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primer_contacto_folios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folio',
            name='telefono_local',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ComentarioEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_encuesta', to='folios.folio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
